### ISSUE TITLE
If I `git rm LICENSE` as instructed in the README, won't I be in violation of the MIT license if I publish my repo?

### ISSUE THREAD

**Issue by evanberkowitz** [scottclowe/python-template-repo#103]
The MIT license says I need to keep the license itself in place.

**Comment by scottclowe** [comment]
The instructions tell you to remove the LICENSE file because:
- The license file that's already there is for the template and is saying the template is owned by me. This is necessary so I can assert that (as the author of the code) I am making it freely available for anyone to use. If you used the existing license file, you would be asserting that I (Scott C. Lowe) am the owner of your code, which is not the case.
- I don't know that you want to license your code under the MIT license and it would be far too presumptive for me to assume that that was in actual fact the license you wanted to use.

Hence we can't reuse the existing license file.

Step 5 instructs you to change the license file to be whichever one you want to use. While I do encourage you to open source your code, I can't assume that you will want to do that. The default property of code that you author is that you own it exclusively and nobody else can use it, and I have to respect that its the choice of the author of the code to actively decide to release their work under an open source license.

**Comment by evanberkowitz** [comment]
If I publish my repo (regardless of the license for my part of the work) pieces of the template will be distributed.  Sure, I will change some information.  As an example, take `__meta__.py`, where I will put my name, my code's information, etc.  But `setup.py` will still be written by you and subject to your copyright.

Removing the license with which you distributed setup.py while continuing to distribute setup.py as part of my repo would be a violation of the MIT license, wouldn't it?

**Comment by scottclowe** [comment]
Ah, sorry, I understand you now!

Yes, I think you are correct - technically users of the template should be including a license for the contents of the template, particularly for the files in the template that they do not need to replace or otherwise modify extensively.

I don't actually want people to have to worry about including a license for that though, so I think I need to change the license from MIT to the UNLICENSE or CC0 which doesn't require the license file be kept with the code.

Thanks for pointing this out.
